### ISSUE TITLE
Unable to run in Metanorma due to error

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#89]
```
IndexError: undefined group name reference: year
  /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/asciidoctor-iso-0.9.3/lib/asciidoctor/iso/ref.rb:70:in `[]'
  /Users/me/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/asciidoctor-iso-0.9.3/lib/asciidoctor/iso/ref.rb:70:in `isorefmatches3'
```

**Comment by ronaldtse** [comment]
@opoudjis you can test this out here: https://github.com/riboseinc/gmt-0009-2012

Just clone and `make clean all`.

**Comment by opoudjis** [comment]
Fixed in asciidoctor-iso
